name: Protocol Land Sync - All Repos
on:
    push:
        branches:
            - 'main'
        paths:
            - 'web-indexer/**'
            - 'search/**'
            - 'npm/**'
    workflow_dispatch:

jobs:
    sync-all:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                repo: ['web-indexer', 'search', 'npm']
            fail-fast: false  # Continue with other repos if one fails
        
        steps:
            - name: 'Checkout repo (default branch)'
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 'Setup node 18'
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'

            - name: 'Install Protocol Land Sync'
              run: npm install -g @protocol.land/sync

            - name: 'Verify Wallet'
              run: |
                if [ -z "${{ secrets.WALLET }}" ]; then
                  echo "Error: WALLET secret is not set"
                  exit 1
                fi

            - name: 'Sync ${{ matrix.repo }} to Protocol Land'
              working-directory: ./${{ matrix.repo }}
              continue-on-error: true  # Don't fail the whole workflow if one sync fails
              run: |
                echo "Starting sync for ${{ matrix.repo }}"
                npx @protocol.land/sync
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  REPO_TITLE: ${{ matrix.repo }}
                  REPO_DESCRIPTION: "Protocol Land sync for ${{ matrix.repo }}"
                  WALLET: ${{ secrets.WALLET }} 